package main

import (
	"fmt"
	"net/http"
	"strings"

	ds "github.com/starfederation/datastar-go/datastar"
)

type chartProps struct {
	Name        string
	Description string
	Value       any
	Unit        string
	Discrete    bool
	Duration    int
	Max         any
}

var charts = []chartProps{
	{"Throttle", "Computed throttle as %", 0, "%", false, 10000, 100},
	{"RPM", "Engine speed in Revolutions Per Minute", 0, "rpm", false, 10000, 10000},
	{"Gear", "Transmission gear", 0, "", true, 10000, 6},
	{"Coolant", "Coolant temperature in celsius", 0, "°C", false, 300000, 120},
	{"Injection Time", "Injector pulse width in milliseconds", 0, "ms", false, 10000, 10},
	{"Grip", "Rider throttle input in %", 0, "%", false, 10000, 100},
	{"TPS", "Throttle plate sensor in %", 0, "%", false, 10000, 100},
}

// IndexHandler is the main entrypoint for the UI
func IndexHandler(w http.ResponseWriter, _ *http.Request) {
	err := Templates.ExecuteTemplate(w, "index", map[string]interface{}{
		"charts": charts,
	})
	if err != nil {
		fmt.Println(err)
		w.WriteHeader(http.StatusInternalServerError)
	}
}

// EventsHandler is called on page load and pushes page changes to the client via SSE,
// based on events generated by the Huskki input source (live / replay)
func EventsHandler(w http.ResponseWriter, r *http.Request) {
	sse := ds.NewSSE(w, r)

	_, ch, cancel := EventHub.Subscribe()
	defer cancel()

	for {
		select {
		case <-r.Context().Done():
			return
		case event := <-ch:
			updateFunc := generatePatch(event)
			err := updateFunc(sse)
			if err != nil {
				fmt.Println(err)
				w.WriteHeader(http.StatusInternalServerError)
				return
			}
		}
	}
}

func buildUpdateChartScript(name string, x int, y float64) string {
	return fmt.Sprintf(`pushData("%s", %d, %f);`, strings.ToLower(name), x, y)
}

// generatePatch takes an event received from the event queue, iterates the charts that are displayed on the UI,
// and returns a closure that can be used to patch the client.
func generatePatch(event map[string]any) func(*ds.ServerSentEventGenerator) error {

	var writer = strings.Builder{}
	var funcs []func(generator *ds.ServerSentEventGenerator) error

	// For each chart see if we have an update and form an SSE update function
	for _, chart := range charts {
		value, ok := event[strings.ToLower(chart.Name)]
		if !ok {
			continue
		}
		timestamp, ok := event["timestamp"]
		if !ok {
			continue
		}

		var v float64
		switch value.(type) {
		case int:
			v = float64(value.(int))
		case float64:
			v = value.(float64)
		default:
			continue
		}

		ts, ok := timestamp.(int)
		if !ok {
			continue
		}

		if value, ok := event[strings.ToLower(chart.Name)]; ok {
			chart.Value = fmt.Sprintf("%v", value)
			err := Templates.ExecuteTemplate(&writer, "chart.value", chart)
			if err != nil {
				fmt.Printf("executing template: %v", err)
			}
		}

		funcs = append(funcs, func(sse *ds.ServerSentEventGenerator) error {
			err := sse.ExecuteScript(buildUpdateChartScript(chart.Name, ts, v))
			return err
		})
	}

	// Main closure
	return func(sse *ds.ServerSentEventGenerator) error {
		// Patch UI elements
		if writer.String() != "" {
			err := sse.PatchElements(writer.String())
			if err != nil {
				return err
			}
		}

		// Exec client-side javascript
		for _, f := range funcs {
			err := f(sse)
			if err != nil {
				return err
			}
		}

		return nil
	}
}
